language:
- node_js
node_js:
- 4.4.3
script:
- npm set dslengine:CONNECTION $CONNECTION 
- npm test
notifications:
  slack:
    secure: WpuOylb3w24/3m0UWdOdt1NVdH969B0wQ8dCvjXajvLll3HvkIviwRC8GZl1yckjau0UXio39IKYjsM2n7ZxZS8YB3McJBRmewnrU2efqovpcGCSSKHnZFPWKZqdPaSpGWd4CsKf3xdCWcUidjsvPMdMkTBzGvisVJrjR/8f9lgVzJa0RDWE1xSbxI39s3d+nOveAVDco3qZckk1OE/Or3wV4oZURN1K/arQ1Lk39uwUdBHHzJLryd81Qxo1OhZD5J0lWN+0JKPt2H+GsxHdZVGAewcmCTm+kSRyprNUWCo0FIhzjHiJlb5Zj/RDBiqq/oj8Xr/TfXBOeJQqmffqJNpfUVUgspggVfwNaSitiQ1L8GB/3fCQDSZVwJPyq641Zi7+TY+rOCwI4NwCnr8QQKzzhQz020UmFjd4LuTRTukPLcVeHhZ8sjnYf/Lxj3GVBU3LT5SmCUQMT5cVz4lgrX1o7R4ZSjYxP9RuYpuYxXXpE9UTSDDL/CG723olXkYi6CbP0lH4kLVdIWzoGgQBAFgSojaGJM16rEXhVh1EHn9yyZ5BuXPO8NlXDEp8b4quObvpdGC6Nhjxcq++5f9w2vhyxNfPpgKUuTmeW1htoE7SReOOS0GPD62pg+UQqRgd1T+edBfdv5fF97k2FdDamS4X4a5Zij5VagJKvetJEtk=
